# --- NVIDIA ---
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
exec-once = nohup awww-daemon &> /dev/null
exec-once = python3 ~/.config/hypr/scripts/music-server.py &
exec-once = ~/.config/hypr/scripts/restore-wallpaper.sh
cursor {
    no_hardware_cursors = true
    use_cpu_buffer = true
}

# --- MONITOR ---
monitor=,preferred,auto,1

# --- ECOSYSTEM ---
ecosystem {
    no_update_news = true
}

# --- AUTOSTART ---
exec-once = hyprpaper
exec-once = waybar

# --- INPUT ---
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
}

device {
    name = elan0524:00-04f3:3215-mouse
    enabled = false
}

# --- GENERAL ---
general {
    gaps_in = 8
    gaps_out = 15
    border_size = 3
    col.active_border = rgba(8839efff) rgba(1e66f5ff) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

# --- DECORATION ---
decoration {
    rounding = 15
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = true
    }
    active_opacity = 1.0
    inactive_opacity = 1.0
    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(cba6f766)
    }
}

# --- ANIMATIONS ---
animations {
    enabled = yes
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    animation = windows, 1, 7, overshot
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default, slide
}
#clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
$mainMod = SUPER
bind = $mainMod, X, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
# --- KEYBINDS ---
$mainMod = SUPER
bind = $mainMod, V, exec, code
bind = $mainMod, S, exec, spotify
bind = $mainMod, Q, exec, kitty
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, C, killactive
bind = $mainMod, L, exec, hyprlock
bind = $mainMod SHIFT, L, exit
bind = $mainMod, D, exec, obsidian
bind = $mainMod, B, exec, blueman-manager
bind = $mainMod, E, exec, brave --app=file:///home/saman/.config/sidebar/sidebar.html --window-size=380,900
bind = $mainMod, W, exec, ~/.config/hypr/scripts/theme.sh
bind = $mainMod, N, exec, hyprsunset -t 5000
bind = $mainMod SHIFT, N, exec, hyprsunset -i
bind = $mainMod, F, togglefloating
bind = , Print, exec, grim -g "$(slurp)" - | tee ~/Pictures/$(date +'%Y-%m-%d-%H%M%S_screenshot.png') | wl-copy

binde = , XF86AudioRaiseVolume, exec, pamixer -i 5
binde = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t
binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
#more workspace
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3

# --- WINDOW RULES ---
source = ~/.config/hypr/UserConfigs/WindowRules.conf
exec-once = nm-applet --indicator
