background {
    monitor =
    path = /home/saman/Pictures/wallpapers/wp6.jpg
    blur_passes = 2
    blur_size = 5
    brightness = 0.4
    contrast = 1.0
    vibrancy = 0.2
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(ef9f27ff)
    font_size = 80
    font_family = FiraCode Nerd Font Bold
    position = 0, 180
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 5
    shadow_color = rgba(00000088)
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %B %d"
    color = rgba(94e2d5ff)
    font_size = 22
    font_family = FiraCode Nerd Font
    position = 0, 90
    halign = center
    valign = center
    shadow_passes = 2
    shadow_color = rgba(00000088)
}

label {
    monitor =
    text = whats the password
    color = rgba(ef9f27aa)
    font_size = 14
    font_family = FiraCode Nerd Font
    position = 0, -60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    outer_color = rgba(ef9f27ff)
    inner_color = rgba(1e1e2e99)
    font_color = rgba(ef9f27ff)
    fade_on_empty = true
    placeholder_text =
    position = 0, -120
    halign = center
    valign = center
    rounding = 10
    check_color = rgba(a6e3a1ff)
    fail_color = rgba(f38ba8ff)
    fail_text = ✗ wrong password
    capslock_color = rgba(f9e2afff)
	check_color = rgba(a6e3a1ff)
fail_color = rgba(f38ba8ff)
fail_text = ✗ wrong password
}
